name: 'Configure Git for push'
description: 'Logs in using GH token and setup Git user'
inputs:
  gh-token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure Git
      shell: bash
      run: |
        gh auth setup-git
        git config --local user.email "quarkus-qe@redhat.com"
        git config --local user.name "QuarkusQE"
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
        GH_REPO: ${{ github.repository }}
