name: 'Extract tests'
description: 'Extracts tests for given Quarkus release tag name'
inputs:
  tag:
    description: "Quarkus release tag"
    required: true
  gh-token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Extract tests for given tag and open PR
      shell: bash
      run: |
        wget -q https://raw.githubusercontent.com/quarkus-qe/quarkus-test-extractor/refs/heads/main/extract-tests.sh
        chmod +x extract-tests.sh
        ./extract-tests.sh -v -p -g "$GH_TOKEN" -b "$RELEASE_TAG"
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
        GH_REPO: ${{ github.repository }}
        RELEASE_TAG: ${{ inputs.tag }}
