name: "Daily release detection and extraction"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
jobs:
  detect-releases:
    name: Detect new Quarkus releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/detect-new-releases
        id: detection
        with:
          gh-token: ${{ secrets.QUARKUS_QE_GH_PUSH_TOKEN }}
    outputs:
      tags: ${{ steps.detection.outputs.tags }}
  extract-tests:
    name: Extract tests from new Quarkus releases
    if: ${{ contains(needs.detect-releases.outputs.tags, '[') }}
    runs-on: ubuntu-latest
    needs: [detect-releases]
    strategy:
      fail-fast: false
      matrix:
        tag: ${{ fromJSON(needs.detect-releases.outputs.tags) }}
    steps:
      - uses: actions/checkout@v4
      - name: Install JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: ./.github/actions/extract-tests
        with:
          tag: ${{ matrix.tag }}
          gh-token: ${{ secrets.QUARKUS_QE_GH_PUSH_TOKEN }}
