name: "Daily release detection and extraction"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
jobs:
  detect-releases:
    name: Detect new Quarkus releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/detect-new-releases
        id: detection
    outputs:
      tags: ${{steps.detection.outputs.tags}}
  extract-tests:
    name: Extract tests from new Quarkus releases
    if: ${{ contains(needs.detect-releases.outputs.tags, 'tag') }}
    runs-on: ubuntu-latest
    needs: [detect-releases]
    strategy:
      fail-fast: false
      matrix:
        includes: ${{ fromJSON(needs.detect-releases.outputs.tags) }}
    steps:
      - uses: actions/checkout@v4
      - name: Install JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true
          cache: 'maven'
        id: install-jdk
      - uses: ./.github/actions/configure-git
      - uses: ./.github/actions/extract-tests
        with:
          tag: ${{ matrix.tag }}
